### ISSUE TITLE
Deploying to firebase hosting fails using 'ng deploy' in Angular 10.

### ISSUE THREAD

**Issue by codethatstack** [angular/angularfire#2584]
Tried deploying Angular application to firebase hosting using the `ng deploy` but fails with an unhandled exception.

### Version info

**Angular:** 10.1.0

**Firebase:** 8.9.0

**AngularFire:**6.0.2

**Other (Node, operating system):** 12.13.1, windows 10

### How to reproduce these conditions

Run the angular deploy command:

> ng deploy

**Steps to set up and reproduce**

**Sample data and security rules**

### Debug output

** Errors in the JavaScript console **

An unhandled exception occurred: workspace.getProjectTargets is not a function
See "C:\Users\antho\AppData\Local\Temp\ng-tHmp0j\angular-errors.log" for further details.

** Error Log **

[error] TypeError: workspace.getProjectTargets is not a function
    at C:\Projects\CodeThatStack\jms\node_modules\@angular\fire\schematics\deploy\builder.js:26:38
    at Generator.next (<anonymous>)
    at fulfilled (C:\Projects\CodeThatStack\jms\node_modules\@angular\fire\schematics\deploy\builder.js:5:58)

** Screenshots **

### Expected behavior

Should build and deploy application to firebase hosting

### Actual behavior

Fails before starting website build.

## Fix 

I don't have much knowledge with the internals of schematics but debugged the issue down to the following in the schematics deploy builder file. I made changes locally and this worked for me. It seems that `workspace.getProjectTargets` is no longer available.

https://github.com/angular/angularfire/blob/master/src/schematics/deploy/builder.ts

Change line 28 from:

`const projectTargets = workspace.getProjectTargets(context.target.project);`

to

`const projectTargets = workspace.getProject(context.target.project);`

**Comment by Splaktar** [comment]
Can you share your workspace file (angular.json)?

Did you run `ng update @angular/cli` when you updated? Did the migrations run?

Can you reproduce this in a new project?

Personally, I switched to `firebase deploy --only hosting` for deployments a while back due to needing to run some other scripts in addition to `ng build --prod` (i.e. Scully). So I haven't been running `ng deploy` since updating to v10.

**Comment by codethatstack** [comment]
I've tried to reproduce in another application and deployment works fine just fine.

What I did notice, is the targets where not defined in the workspace object which may have something to do with it.

I'm closing this issue as it only happened on my project, plus I've moved away from ng deploy to using firebase deploy myself.
