### ISSUE TITLE
AngularFire 7.2 doesn't compile with latest Angular 13.1 and Typescript 4.5

### ISSUE THREAD

**Issue by anisabboud** [angular/angularfire#3090]
Update Angular & Typescript to latest (13.1.0 and 4.5.3) => `ng serve` errors in the terminal:

Error: node_modules/@angular/fire/compat/proxy.d.ts:7:49 - error TS2344: Type 'T[K]' does not satisfy the constraint '(...args: any) => any'.
![image](https://user-images.githubusercontent.com/5672108/145548137-63abad6d-38d3-40cc-b88f-7835b7d01fba.png)

Caused by this file: https://github.com/angular/angularfire/blob/master/src/compat/proxy.ts
Latest version of Typescript (4.5.3) doesn't like T[K].

**Comment by ProtoScott** [comment]
I'm also having the same problem:




### Version info

**Angular:**
13.1.1

**Firebase:**
9.0.0

**AngularFire:**
7.0.4

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
Chrome

### How to reproduce these conditions

**Failing test unit, Stackblitz demonstrating the problem**

N/A

Upgrade to Typescript 4.5.3, Angular 13.1.1, AngularFire 7.0.4



**Sample data and security rules**

N/a

### Debug output

** Errors in the JavaScript console **
Error: node_modules/@angular/fire/compat/proxy.d.ts:7:49 - error TS2344: Type 'T[K]' does not satisfy the constraint '(...args: any) => any'.
  Type 'T[FunctionPropertyNames<T>]' is not assignable to type '(...args: any) => any'.
    Type 'T[T[keyof T] extends Function ? keyof T : never]' is not assignable to type '(...args: any) => any'.
      Type 'T[keyof T]' is not assignable to type '(...args: any) => any'.
        Type 'T[string] | T[number] | T[symbol]' is not assignable to type '(...args: any) => any'.
          Type 'T[string]' is not assignable to type '(...args: any) => any'.

7     [K in FunctionPropertyNames<T>]: ReturnType<T[K]> extends Promise<any> ? K : never;

** Output from `firebase.database().enableLogging(true);` **
N/A

** Screenshots **

![image](https://user-images.githubusercontent.com/73667130/145651707-bba25435-7e68-411b-8d3a-b83ebf26604d.png)

### Expected behavior

Angular app compiles without any problems.

### Actual behavior

Angular App no longer compiles

**Comment by ProtoScott** [comment]
A temporary fix for this is to revert typescript back to 4.4.4:

`npm install typescript@4.4.4`

**Comment by Ahmed4812** [comment]
Same problem here!

**Comment by Helioty** [comment]
Same problem

**Comment by justjoshin83** [comment]
i am having the same issue.  Any assistance would be much appreciated

**Comment by MedLahkime** [comment]
Same issue with the following 
   angular : 3.1.0",
    "@angular/fire": "^7.2.0",
    "firebase": "^9.0.0",
    "rxfire": "^6.0.0"

**Comment by carlosdag28** [comment]
Same issue with the following:
"@angular/core": "~13.1.0",
"@angular/fire": "^7.2.0",
"firebase": "^9.6.1"

**Comment by jamesdaniels** [comment]
Set `skipLibCheck: true` in your tsconfig for now.

**Comment by Darrow8** [comment]
`skipLibCheck: true` worked for me!

**Comment by mikgross** [comment]
Thanks @jamesdaniels !!

**Comment by araya27** [comment]
@jamesdaniels thanks!!!

**Comment by GoSkiMN** [comment]
`skipLibCheck: true`  did NOT work for me.

**Comment by Li0n-0** [comment]
`skipLibCheck: true` must be inside `compilerOptions` @GoSkiMN 

Can confirm the issue with :
 "@angular/core": "~13.1.1",
  "@angular/fire": "^7.2.0",

**Comment by fennrussel** [comment]
Add this 2 lines inside compilerOptions in your tsconfig.json

"skipDefaultLibCheck": true,
"skipLibCheck": true,

**Comment by Mutti-u-rehman** [comment]
> npm install typescript@4.4.4

Thanks

**Comment by EmmanuelDeLaion** [comment]
I put "skipLibCheck": true inside compilerOptions in the tsconfig.json file and it works for me for now

**Comment by MrMartinez** [comment]
> Set `skipLibCheck: true` in your tsconfig for now.

Al principo no me funcinaba porque estaba corriendo el ng build, ahi seguia el error; pero con ng serve la corre normal

**Comment by IslamElKassas** [comment]
Updating typescript to v4.5.5 does not work, skipLibCheck : true worked for me

**Comment by fetahokey** [comment]
Same here, thank you @ProtoScott

**Comment by NashIlli** [comment]
same problem here!
