### ISSUE TITLE
Pre-rendering error after update (6.0.5 → 6.1.1)

### ISSUE THREAD

**Issue by mazlano27** [angular/angularfire#2671]
### Version info

**Angular:11.0.1**

**Firebase:8.0.2**

**AngularFire:6.1.1**

### How to reproduce these conditions

After updating to v6.1.1 → angular pre-rendering yields the following error:

`TypeError: app.firestore is not a function`

I've tried to delete node_modules and package-lock.json and re-install packages but the error persist. Rolling back to v6.0.5 fixes the issue

### Expected behavior

Should be able to pre-render routes successfully 

### Actual behavior

Unable to pre-render routes successfully

**Comment by mazlano27** [comment]
**Update:**

When updating from Angular 9 → 10, I had added "@firebase/firestore" as an external dependency in angular.json to allow for pre-rendering. 

After updating to @angular/fire 6.1.1 and removing the external dependency from angular.json, the pre-rendering seems to be working once more.

**Comment by jamesdaniels** [comment]
Closing in favor of pinned #2686
