### ISSUE TITLE
SSR fails after update to v7 using ng-update "_firebase_app_compat__WEBPACK_IMPORTED_MODULE_0__.registerVersion is not a function"

### ISSUE THREAD

**Issue by mazlano27** [angular/angularfire#2903]
### Version info

**Angular: 12**

**Firebase: 9**

**AngularFire:7**

### How to reproduce these conditions

Updating a SSR (firebase cloud functions) project from V6 → V7

### Debug output

`Error: Error occurred while parsing your function triggers.
TypeError: _firebase_app_compat__WEBPACK_IMPORTED_MODULE_0__.registerVersion is not a function
    at Object.59607 (/Users/Azlan_Mac/Desktop/Dev/Project-X/ng-dist/ng-firebase-project-ssr-server/main.js:1:2898287)
    at __webpack_require__ (/Users/Azlan_Mac/Desktop/Dev/Project-X/ng-dist/ng-firebase-project-ssr-server/main.js:1:3503949)
    at Object.88939 (/Users/Azlan_Mac/Desktop/Dev/Project-X/ng-dist/ng-firebase-project-ssr-server/main.js:1:1013500)
    at __webpack_require__ (/Users/Azlan_Mac/Desktop/Dev/Project-X/ng-dist/ng-firebase-project-ssr-server/main.js:1:3503949)
    at Object.1325 (/Users/Azlan_Mac/Desktop/Dev/Project-X/ng-dist/ng-firebase-project-ssr-server/main.js:1:994398)
    at __webpack_require__ (/Users/Azlan_Mac/Desktop/Dev/Project-X/ng-dist/ng-firebase-project-ssr-server/main.js:1:3503949)
    at Object.50384 (/Users/Azlan_Mac/Desktop/Dev/Project-X/ng-dist/ng-firebase-project-ssr-server/main.js:1:2883286)
    at __webpack_require__ (/Users/Azlan_Mac/Desktop/Dev/Project-X/ng-dist/ng-firebase-project-ssr-server/main.js:1:3503949)
    at /Users/Azlan_Mac/Desktop/Dev/Project-X/ng-dist/ng-firebase-project-ssr-server/main.js:1:4820209
    at /Users/Azlan_Mac/Desktop/Dev/Project-X/ng-dist/ng-firebase-project-ssr-server/main.js:1:4870320
npm ERR! code ELIFECYCLE`

### Expected behavior

When updating to v7 from v6 using ng-update, deployment of SSR function should work as before

### Actual behavior

Deployment of SSR function no longer working. Rolling back to v6 fixes the issue.

**Comment by chakrachi** [comment]
same issue here

**Comment by jamesdaniels** [comment]
closing here as It should be addressed in 7.0.1 of the Firebase JS SDK. thanks @Feiyang1

**Comment by mazlano27** [comment]
@jamesdaniels I'm no longer able to run the "ng update @angular/fire" schematic after the update.

`❯ Update @angular/fire to v7.
✖ Migration failed: The "path" argument must be of type string. Received undefined
  See "/private/var/folders/_8/g0bkbl8s2pj6wyzc3g76rfhr0000gn/T/ng-St0QKH/angular-errors.log" for further details.`

The log file shows → 
`[error] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.join (path.js:1110:7)
    at /Users/Azlan_Mac/Desktop/Dev/Project-X/node_modules/@angular/fire/schematics/update/v7/index.js:45:77
    at Array.map (<anonymous>)
    at /Users/Azlan_Mac/Desktop/Dev/Project-X/node_modules/@angular/fire/schematics/update/v7/index.js:45:58
    at MergeMapSubscriber.project (/Users/Azlan_Mac/Desktop/Dev/Project-X/node_modules/@angular-devkit/schematics/src/rules/call.js:75:24)
    at MergeMapSubscriber._tryNext (/Users/Azlan_Mac/Desktop/Dev/Project-X/node_modules/rxjs/internal/operators/mergeMap.js:67:27)
    at MergeMapSubscriber._next (/Users/Azlan_Mac/Desktop/Dev/Project-X/node_modules/rxjs/internal/operators/mergeMap.js:57:18)
    at MergeMapSubscriber.Subscriber.next (/Users/Azlan_Mac/Desktop/Dev/Project-X/node_modules/rxjs/internal/Subscriber.js:66:18)
    at Observable._subscribe (/Users/Azlan_Mac/Desktop/Dev/Project-X/node_modules/rxjs/internal/util/subscribeToArray.js:5:20)`

**Comment by jamesdaniels** [comment]
@mazlano27 that’s most certainly an unrelated error. Can you open a new issue and provide your exact version numbers? And as much environment detail as you can?

**Comment by mazlano27** [comment]
@jamesdaniels - will do

**Comment by thervl** [comment]
Thanks for the support @jamesdaniels 
Struggling with the following error and can't figure out the source
Haven't changed anything in the server.ts during the latest upgrade.

2021-09-06T07:22:31.934Z ? ssr: Provided module can't be loaded.
2021-09-06T07:22:31.934Z ? ssr: Is there a syntax error in your code?
2021-09-06T07:22:31.934Z ? ssr: Detailed stack trace: TypeError: (0 , _firebase_app__WEBPACK_IMPORTED_MODULE_0__.registerVersion) is not a function
2021-09-06T07:22:31.934Z ? ssr:     at Object.44596 (/workspace/dist/server/main.js:1:4333120)
2021-09-06T07:22:31.934Z ? ssr:     at __webpack_require__ (/workspace/dist/server/main.js:1:4932219)
2021-09-06T07:22:31.934Z ? ssr:     at Object.90127 (/workspace/dist/server/main.js:1:1311681)
2021-09-06T07:22:31.934Z ? ssr:     at __webpack_require__ (/workspace/dist/server/main.js:1:4932219)
2021-09-06T07:22:31.934Z ? ssr:     at /workspace/dist/server/main.js:1:6263592
2021-09-06T07:22:31.934Z ? ssr:     at /workspace/dist/server/main.js:1:6365473
2021-09-06T07:22:31.934Z ? ssr:     at Object.<anonymous> (/workspace/dist/server/main.js:1:6365705)
2021-09-06T07:22:31.934Z ? ssr:     at Module._compile (internal/modules/cjs/loader.js:1085:14)
2021-09-06T07:22:31.934Z ? ssr:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
2021-09-06T07:22:31.934Z ? ssr:     at Module.load (internal/modules/cjs/loader.js:950:32)
2021-09-06T07:22:31.935Z ? ssr: Could not load the function, shutting down.
2021-09-06T07:22:32.832945136Z E ssr: Function cannot be initialized. Error: function terminated. Recommended action: inspect logs for termination reason. Additional troubleshooting documentation can be found at https://cloud.google.com/functions/docs/troubleshooting#logging

Package:

    "@angular-devkit/core": "^12.2.3",
    "@angular-devkit/schematics": "^12.2.3",
    "@angular-material-extensions/google-maps-autocomplete": "^6.2.2",
    "@angular/animations": "^12.2.3",
    "@angular/cdk": "^12.2.3",
    "@angular/common": "^12.2.3",
    "@angular/compiler": "^12.2.3",
    "@angular/core": "^12.2.3",
    "@angular/fire": "^7.0.3",
    "@angular/flex-layout": "^11.0.0-beta.33",
    "@angular/forms": "^12.2.3",
    "@angular/material": "^12.2.3",
    "@angular/material-moment-adapter": "^12.2.3",
    "@angular/platform-browser": "^12.2.3",
    "@angular/platform-browser-dynamic": "^12.2.3",
    "@angular/platform-server": "^12.2.4",
    "@angular/router": "^12.2.3",
    "@angular/service-worker": "^12.2.3",
    "@nguniversal/express-engine": "^12.1.0",
    "@schematics/angular": "^11.1.4",
    "@types/googlemaps": "3.43.3",
    "chokidar": "^3.4.2",
    "core-js": "^3.6.5",
    "express": "^4.15.2",
    "firebase": "^9.0.1",

**Comment by thervl** [comment]
> ### Version info
> **Angular: 12**
> 
> **Firebase: 9**
> 
> **AngularFire:7**
> 
> ### How to reproduce these conditions
> Updating a SSR (firebase cloud functions) project from V6 → V7
> 
> ### Debug output
> `Error: Error occurred while parsing your function triggers. TypeError: _firebase_app_compat__WEBPACK_IMPORTED_MODULE_0__.registerVersion is not a function at Object.59607 (/Users/Azlan_Mac/Desktop/Dev/Project-X/ng-dist/ng-firebase-project-ssr-server/main.js:1:2898287) at __webpack_require__ (/Users/Azlan_Mac/Desktop/Dev/Project-X/ng-dist/ng-firebase-project-ssr-server/main.js:1:3503949) at Object.88939 (/Users/Azlan_Mac/Desktop/Dev/Project-X/ng-dist/ng-firebase-project-ssr-server/main.js:1:1013500) at __webpack_require__ (/Users/Azlan_Mac/Desktop/Dev/Project-X/ng-dist/ng-firebase-project-ssr-server/main.js:1:3503949) at Object.1325 (/Users/Azlan_Mac/Desktop/Dev/Project-X/ng-dist/ng-firebase-project-ssr-server/main.js:1:994398) at __webpack_require__ (/Users/Azlan_Mac/Desktop/Dev/Project-X/ng-dist/ng-firebase-project-ssr-server/main.js:1:3503949) at Object.50384 (/Users/Azlan_Mac/Desktop/Dev/Project-X/ng-dist/ng-firebase-project-ssr-server/main.js:1:2883286) at __webpack_require__ (/Users/Azlan_Mac/Desktop/Dev/Project-X/ng-dist/ng-firebase-project-ssr-server/main.js:1:3503949) at /Users/Azlan_Mac/Desktop/Dev/Project-X/ng-dist/ng-firebase-project-ssr-server/main.js:1:4820209 at /Users/Azlan_Mac/Desktop/Dev/Project-X/ng-dist/ng-firebase-project-ssr-server/main.js:1:4870320 npm ERR! code ELIFECYCLE`
> 
> ### Expected behavior
> When updating to v7 from v6 using ng-update, deployment of SSR function should work as before
> 
> ### Actual behavior
> Deployment of SSR function no longer working. Rolling back to v6 fixes the issue.

Hi @mazlano27, have you figured out how to fix this error using v7?

**Comment by mazlano27** [comment]
> > ### Version info
> > **Angular: 12**
> > **Firebase: 9**
> > **AngularFire:7**
> > ### How to reproduce these conditions
> > Updating a SSR (firebase cloud functions) project from V6 → V7
> > ### Debug output
> > `Error: Error occurred while parsing your function triggers. TypeError: _firebase_app_compat__WEBPACK_IMPORTED_MODULE_0__.registerVersion is not a function at Object.59607 (/Users/Azlan_Mac/Desktop/Dev/Project-X/ng-dist/ng-firebase-project-ssr-server/main.js:1:2898287) at __webpack_require__ (/Users/Azlan_Mac/Desktop/Dev/Project-X/ng-dist/ng-firebase-project-ssr-server/main.js:1:3503949) at Object.88939 (/Users/Azlan_Mac/Desktop/Dev/Project-X/ng-dist/ng-firebase-project-ssr-server/main.js:1:1013500) at __webpack_require__ (/Users/Azlan_Mac/Desktop/Dev/Project-X/ng-dist/ng-firebase-project-ssr-server/main.js:1:3503949) at Object.1325 (/Users/Azlan_Mac/Desktop/Dev/Project-X/ng-dist/ng-firebase-project-ssr-server/main.js:1:994398) at __webpack_require__ (/Users/Azlan_Mac/Desktop/Dev/Project-X/ng-dist/ng-firebase-project-ssr-server/main.js:1:3503949) at Object.50384 (/Users/Azlan_Mac/Desktop/Dev/Project-X/ng-dist/ng-firebase-project-ssr-server/main.js:1:2883286) at __webpack_require__ (/Users/Azlan_Mac/Desktop/Dev/Project-X/ng-dist/ng-firebase-project-ssr-server/main.js:1:3503949) at /Users/Azlan_Mac/Desktop/Dev/Project-X/ng-dist/ng-firebase-project-ssr-server/main.js:1:4820209 at /Users/Azlan_Mac/Desktop/Dev/Project-X/ng-dist/ng-firebase-project-ssr-server/main.js:1:4870320 npm ERR! code ELIFECYCLE`
> > ### Expected behavior
> > When updating to v7 from v6 using ng-update, deployment of SSR function should work as before
> > ### Actual behavior
> > Deployment of SSR function no longer working. Rolling back to v6 fixes the issue.
> 
> Hi @mazlano27, have you figured out how to fix this error using v7?



> > ### Version info
> > **Angular: 12**
> > **Firebase: 9**
> > **AngularFire:7**
> > ### How to reproduce these conditions
> > Updating a SSR (firebase cloud functions) project from V6 → V7
> > ### Debug output
> > `Error: Error occurred while parsing your function triggers. TypeError: _firebase_app_compat__WEBPACK_IMPORTED_MODULE_0__.registerVersion is not a function at Object.59607 (/Users/Azlan_Mac/Desktop/Dev/Project-X/ng-dist/ng-firebase-project-ssr-server/main.js:1:2898287) at __webpack_require__ (/Users/Azlan_Mac/Desktop/Dev/Project-X/ng-dist/ng-firebase-project-ssr-server/main.js:1:3503949) at Object.88939 (/Users/Azlan_Mac/Desktop/Dev/Project-X/ng-dist/ng-firebase-project-ssr-server/main.js:1:1013500) at __webpack_require__ (/Users/Azlan_Mac/Desktop/Dev/Project-X/ng-dist/ng-firebase-project-ssr-server/main.js:1:3503949) at Object.1325 (/Users/Azlan_Mac/Desktop/Dev/Project-X/ng-dist/ng-firebase-project-ssr-server/main.js:1:994398) at __webpack_require__ (/Users/Azlan_Mac/Desktop/Dev/Project-X/ng-dist/ng-firebase-project-ssr-server/main.js:1:3503949) at Object.50384 (/Users/Azlan_Mac/Desktop/Dev/Project-X/ng-dist/ng-firebase-project-ssr-server/main.js:1:2883286) at __webpack_require__ (/Users/Azlan_Mac/Desktop/Dev/Project-X/ng-dist/ng-firebase-project-ssr-server/main.js:1:3503949) at /Users/Azlan_Mac/Desktop/Dev/Project-X/ng-dist/ng-firebase-project-ssr-server/main.js:1:4820209 at /Users/Azlan_Mac/Desktop/Dev/Project-X/ng-dist/ng-firebase-project-ssr-server/main.js:1:4870320 npm ERR! code ELIFECYCLE`
> > ### Expected behavior
> > When updating to v7 from v6 using ng-update, deployment of SSR function should work as before
> > ### Actual behavior
> > Deployment of SSR function no longer working. Rolling back to v6 fixes the issue.
> 
> Hi @mazlano27, have you figured out how to fix this error using v7?

Hi @thervl

After running ng update @angular/fire using the latest version (7.0.4) addressed this issue for some of my projects. I also had to ensure that firebase was the latest version in my cloud functions directory (9.0.1) to ensure SSR was working.
