### ISSUE TITLE
Error with Analytics after updating to v17

### ISSUE THREAD

**Issue by sorcamarian** [angular/angularfire#3491]
```
homepage.component.ts:1194 ERROR TypeError: app.analytics is not a function
    at angular-fire-compat-analytics.mjs:128:39
    at ɵcacheInstance (angular-fire-compat.mjs:146:29)
    at angular-fire-compat-analytics.mjs:127:34
    at map.js:7:37
    at OperatorSubscriber._next (OperatorSubscriber.js:13:21)
    at OperatorSubscriber.next (Subscriber.js:31:18)
    at subscribe.innerSubscriber (switchMap.js:14:144)
    at OperatorSubscriber._next (OperatorSubscriber.js:13:21)
    at OperatorSubscriber.next (Subscriber.js:31:18)
    at innerFrom.js:61:28
```
I just updated to Angular 17 and AngularFire 17

**Comment by sorcamarian** [comment]
I updated **firebase** to v10 from v9 and now I don't see errors.

I see that AngularFire requires v12 of **firebase-tools** and not the latest v13

**Comment by armando-navarro** [comment]
Thanks for following up, and glad you got it working. As you found, aligning firebase to v10 with `@angular/fire 17` clears the 'app.analytics is not a function' error, since that AngularFire release expects the matching firebase major. The firebase-tools version is separate from the firebase SDK version, so that difference is expected and harmless.

I'll close this as resolved; if the error returns on current versions, feel free to open a new issue.
