### ISSUE TITLE
Error building and deploying project - ng build

### ISSUE THREAD

**Issue by akshaybabloo** [angular/angularfire#2785]
### Version info

**Angular:** 11.2.7

**Firebase:** 9.8.0

**AngularFire:** 6.1.4

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** macOS 10.15.7

### How to reproduce these conditions

**Failing test unit, Stackblitz demonstrating the problem**

Any simple project should work

**Steps to set up and reproduce**

1. Create an Angular project
2. Then - `ng add @angular/fire` and follow the instructions
3. Then - `ng deploy` to firebase

**Sample data and security rules**

None

### Debug output

** Errors in the JavaScript console **

None

** Output from `firebase.database().enableLogging(true);` **

N/A

** Screenshots **

![Screen Shot 2021-03-28 at 7 51 02 PM](https://user-images.githubusercontent.com/7360286/112744709-f59b6880-8ffe-11eb-913d-af173cb3e648.png)

### Expected behavior

The project should build and upload to firebase hosting

### Actual behavior

The project builds but then in the end I get - `firebaseTools.logger.add is not a function` error and then exists the program

The error happens here:

https://github.com/angular/angularfire/blob/fb269959f32fbd987d5e67619dcd4cd289310365/src/schematics/deploy/actions.ts#L257

**Comment by QualBean** [comment]
Have you added  firebase hosting config to your environments?

**Comment by akshaybabloo** [comment]
@QualBean yes I did

**Comment by QualBean** [comment]
Installing firebase-tools in your global environment.
`sudo npm install -g firebase-tools `

**Comment by akshaybabloo** [comment]
I have already done that too @QualBean

**Comment by akshaybabloo** [comment]
Works in v6.1.5

**Comment by jamesdaniels** [comment]
Ah yes, this was due to an internal change in the firebase-tools node API. I fixed in 6.1.5 and forgot to put in the release notes.

**Comment by BCusack** [comment]
change to  `firebaseTools.logger.logger.add(`  works for now in \node_modules\@angular\fire\schematics\deploy\actions.js
Just for a quick resolve - really really shouldn't edit node_modules, will be tracking for fix.
