### ISSUE TITLE
Error: node_modules/@firebase/auth-compat/dist/auth-compat/index.d.ts:53:213 - error TS1005: ',' expected.

### ISSUE THREAD

**Issue by nolafs** [angular/angularfire#3287]
Hi,

I got no idea what is going on. It was working just fine for month but suddenly after updating to 7.2.1, I am getting the following error

Error: node_modules/@firebase/auth-compat/dist/auth-compat/index.d.ts:53:213 - error TS1005: ',' expected.
53 import { type User, type Unsubscribe, type ActionCodeInfo, type UserCredential, type Auth, type IdTokenResult, type MultiFactorError, type MultiFactorResolver, type PopupRedirectResolver, type Dependencies, type AuthCredential, type ApplicationVerifier, type ConfirmationResult, type AuthProvider, type MultiFactorUser, type NextOrObserver, type ErrorFn, type CompleteFn, type ActionCodeSettings, type Persistence, type PhoneAuthCredential } from "@firebase/auth";

### Version info

Angular: 13.0.2
firebase-admin: "^9.11.1",
firebase-functions: "^3.6.0",
firebase-tools: "^9.23.0",

@angular/fire : ^7.2.1,

Node: 16

**Comment by kartiksolanki** [comment]
I am facing this same exact issues. Any resolution?

**Comment by Xqwer** [comment]
Same issue, completely out of the blue. No new deps/changes in package.json/tsconfig.json.
After a while we just manually installed deps 1-1 after checking them against a working project.
All @angular/xxxx were set to ~13.3.x, rxjs to ~7.5.0 and typescript: ~4.6.2.
This was extremely frustrating.. Good luck, all.

**Comment by Sahil-shah-167** [comment]
Facing same issue .

**Comment by ArunAnandSeven** [comment]
facing same issue. how to solve this?

**Comment by danielmmf** [comment]
aqui está a linha corrigida
import { User, Unsubscribe, ActionCodeInfo, UserCredential, Auth, IdTokenResult, MultiFactorError, MultiFactorResolver, PopupRedirectResolver, Dependencies, AuthCredential, ApplicationVerifier, ConfirmationResult, AuthProvider, MultiFactorUser, NextOrObserver, ErrorFn, CompleteFn, ActionCodeSettings, Persistence, PhoneAuthCredential } from "@firebase/auth";

**Comment by aakashahpl** [comment]
Facing the same issue. Did anyone got a solution to this?

**Comment by armando-navarro** [comment]
This error comes from a TypeScript version too old to parse the inline `type` import modifiers in `@firebase/auth-compat`'s type definitions, which require TypeScript 4.5 and later; every report here is from an Angular 12-13 / TS 4.3-4.4 stack.

Upgrading TypeScript (Angular 14+ ships TS 4.6+) resolves it, and toolchains on TypeScript 4.5 or later are unaffected.

Closing as resolved by upgrading TypeScript; please open a fresh issue if a comparable parse error appears on a current toolchain.
