### ISSUE TITLE
AppCheck stopped working with upgrade from 7.0.4 to 7.5.0 and is throwing No Firebase App '[DEFAULT]' has been created

### ISSUE THREAD

**Issue by Yetispapa** [angular/angularfire#3311]
### Version info

**Angular:**
15.1.2

**Firebase:**
9.23.3

**AngularFire:**
7.5.0

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

Node: 18.13.0
Package Manager: yarn 1.22.19
OS: darwin arm64

Angular: 15.1.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1501.2
@angular-devkit/build-angular   15.1.2
@angular-devkit/core            15.1.2
@angular-devkit/schematics      15.1.2
@angular/cli                    15.1.2
@angular/fire                   7.5.0
@schematics/angular             15.1.2
rxjs                            6.6.7
typescript                      4.9.4

### How to reproduce these conditions

I upgrade from Angular 12 to Angular 15. With that, I upgrade AngularFire from 7.0.4 to 7.5.0. The overall upgrade of Angular seemed alright, but unfortunately my AppCheck stopped working. In the console, I have the AppCheck enabled via Recaptcha. More details of my setup are in the steps to reproduce.

**Steps to set up and reproduce**

In **app.modules.ts**

```
  imports: [
    AngularFireModule.initializeApp(environment.firebase),
    provideFirebaseApp(() => initializeApp(environment.firebase)),
    provideAppCheck(() => {
          const provider = new ReCaptchaV3Provider(environment.recaptcha);
          
          // calling getApps() is returning an empty array

          // the line getApp() is throwing: No Firebase App '[DEFAULT]' has been created
          
          return initializeAppCheck(getApp(), {
            provider,
            isTokenAutoRefreshEnabled: true,
          });
        })
  ],
```

As mentioned in the code comments, `getApp()` is throwing the exception: `No Firebase App '[DEFAULT]' has been created` and let angular run in a white page. I tried some debugging and `getApps()` is returning an empty array. So it seems, that there is no Firebase app created in the first place. 

I tried several different approaches, which you can find in the tickets, Stackoverflow or documentation like:

Use `provideFirestore`
```

    provideFirebaseApp(() => initializeApp({ ... })),
    provideFirestore(() => getFirestore()),
```

Use `undefined` instead of `getApp()`
        ```
const provider = new ReCaptchaV3Provider(environment.recaptcha3SiteKey);
        return initializeAppCheck(undefined, { provider, isTokenAutoRefreshEnabled: true });
```

Adding this to providers:
`{ provide: FIREBASE_OPTIONS, useValue: environment.firebase },`

I want to point out, that if I comment out the AppCheck section, my app works and I get a permission exception because of the missing app check token as expected. Furthermore, this worked in 7.0.4.

### Debug output

`ERROR Error: Uncaught (in promise): FirebaseError: Firebase: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp() (app/no-app).`

### Expected behavior

AppCheck is initialized with a correct FirebaseApp instance

### Actual behavior

No FirebaseApp instance is available and AppCheck initialization is throwing an exception, as described in above

**Comment by Yetispapa** [comment]
Anyone?

**Comment by Yetispapa** [comment]
@jamesdaniels could you maybe help me here?

**Comment by vadimwe** [comment]
+1

**Comment by georgstrieder** [comment]
+1

**Comment by rinebob** [comment]
Has anyone found a solution?  I'm getting this error trying to initialize an Auth instance.  

main.ts:6 ERROR FirebaseError: Firebase: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp() (app-compat/no-app).

app.module.ts
import { connectFirestoreEmulator, getFirestore, provideFirestore, enableMultiTabIndexedDbPersistence } from '@angular/fire/firestore';
import { getAuth, provideAuth } from '@angular/fire/auth';
import { initializeApp, provideFirebaseApp } from '@angular/fire/app';

imports: [
...
provideFirebaseApp(() => initializeApp(environment.firebase)),
    provideAuth(() => {
      const auth = getAuth();
      if (environment.useEmulators) {
        connectAuthEmulator(auth, 'http://localhost:9099', {disableWarnings: false});
      }
      return auth;
    }),
]

login.component.ts
 ui: firebaseui.auth.AuthUI;
constructor() {}
ngOnInit(): void {
    this.ui = new firebaseui.auth.AuthUI(firebase.auth());
    this.ui.start('#firebaseui-auth-container', this.firebaseuiConfig);
// this also doesn't work:
    if (this.ui.isPendingRedirect()) {
      this.ui.start('#firebaseui-auth-container', this.firebaseuiConfig);
    }

  }

login.component.html

div class="auth-container" id="firebaseui-auth-container"></div

Here's a screenshot with the debugger paused on the error 

![image](https://user-images.githubusercontent.com/39388557/235371445-9c72ade2-7c65-4442-80fd-a22212b16bd9.png)

**Comment by rinebob** [comment]
Hi @Di-Strix - great tip - did just what you said and it worked immediately.  Thanks!  Once that got fixed the firebaseui worked right away.

**Comment by Mobiletainment** [comment]
The only workaround for me was to downgrade from `firebase@9.23.0` to `firebase@9.17.2`

**Comment by ekselys** [comment]
Same error here but with these dependencies:

```json
"@angular/xxxx": "16.1.4",
"@angular/fire": "7.6.1",
```

I get the error directly when invoking getAuth():

```typescript
@NgModule({
    declarations: [],
    imports: [
        CommonModule,
        provideFirebaseApp(() => initializeApp(environment.firebase)),
        provideAuth(() => {
            // ERRROR HERE
            const auth = getAuth();
            setPersistence(auth, { type: 'LOCAL' });
            if (!environment.production) {
                connectAuthEmulator(auth, 'http://127.0.0.1:9099');
            }
            return auth;
        }),
    ]
})
export class FirebaseModule {
}
```


any tips/advice?

**Comment by armando-navarro** [comment]
The thread traces this to two old-version causes: mixing the compat and modular providers (`AngularFireModule.initializeApp` together with `provideFirebaseApp`), and a dependency-resolution problem specific to firebase 9.23.x that others fixed by pinning 9.17.2 or by clearing `node_modules` and reinstalling. Those conditions are tied to @angular/fire 7.x and firebase 9.

If `'No Firebase App [DEFAULT]'` still occurs on a current version, please open a new issue with a minimal reproduction.
